### ISSUE TITLE
SyntaxError since API 1.2.1

### ISSUE THREAD

**Issue by angelkenneth** [Telerivet/telerivet-python-client#2]
Since upgrading to the class API 1.2.0 to 1.2.1, this exception gets raised:

```
>>> import telerivet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{...}/python3.6/site-packages/telerivet/__init__.py", line 150
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

This form of Exception catching is no longer support on Python 3 [[1]](https://www.python.org/dev/peps/pep-3110/#grammar-changes), and since Python 2.6 [[2]](https://docs.python.org/2/whatsnew/2.6.html#pep-3110-exception-handling-changes), the form bellow is now preferred:

```python
try:
    res = response.json()
except ValueError as e:
    raise IOError("Unexpected response from Telerivet API (HTTP {}): {}".format(response.status_code, response.content))
```

I will make a PR request with the fix, unless this library needs to support Python 2.5 (and below) syntax, do reply if so.

**Comment by youngj** [comment]
Thanks for letting us know! This library doesn't need to support Python 2.5 and below, so I updated it as you suggested in version 1.2.2.
