### ISSUE TITLE
Python 3 bytes vs string error

### ISSUE THREAD

**Issue by asokratis** [Telerivet/telerivet-python-client#3]
When the parameters I pass are long (i.e. importing multiple contacts in one API call), I see the code compresses the data. I get some [bytes vs string error](https://eli.thegreenplace.net/2012/01/30/the-bytesstr-dichotomy-in-python-3) and [editing a part to UTF 8 within the compression part of the code ](https://github.com/asokratis/telerivet-python-client/commit/060345ab5cbb6080bb0bc76c330094cae937fc5c) has worked so well so far ever since.   

My question would be does the source code needs the fix from the link above to support Python 3 long parameters or are there alternative ways that I have to configure my environment so I do not get this error?

**Comment by youngj** [comment]
Thanks for reporting this. It was fixed in version 1.4.4.
