### ISSUE TITLE
Make package pip installable

### ISSUE THREAD

**Issue by znicholasbrown** [Telerivet/telerivet-python-client#5]
Hi all!

I'm deploying some Prefect Flows that take advantage of the Telerivet Python Client; right now this is the only dependency that needs to be manually installed rather than using a package manager like `pip`.

Is it possible to publish this to `conda-forge` or `pip`? I've used the Node client in the past and it was nice to be able to `npm install` that.

**Comment by youngj** [comment]
Thanks for the suggestion. The Python client library can now be installed via `pip` : https://pypi.org/project/telerivet/

**Comment by znicholasbrown** [comment]
Thanks @youngj!
